### ISSUE TITLE
Downloading_Image

### ISSUE THREAD

**Issue by amandeep7i** [StatsGary/Tensorflow_Tutorials#1]
When we are downloading the image through this scrapper the images are of low res. What can we do if we want to get higher-resolution images? Please specify

**Comment by StatsGary** [comment]
You would have to visit each URL and extract the image directly. That may fail though.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Aman Kumar ***@***.***>
Sent: Friday, December 16, 2022 7:21:39 AM
To: StatsGary/Tensorflow_Tutorials ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StatsGary/Tensorflow_Tutorials] Downloading_Image (Issue #1)


When we are downloading the image through this scrapper the images are of low res. What can we do if we want to get higher-resolution images? Please specify

**Comment by amandeep7i** [comment]
Is there anyway to make it for high res

**Comment by StatsGary** [comment]
The resolution will be image on image dependent, but I don't know if you will get super resolution from thumbnails.
